apiVersion: v1
kind: Secret
metadata:  
  name: "{{ .Values.backend.name }}"
  labels:
    app: "{{ .Values.backend.name }}"
    namespace: "{{ .Release.Namespace }}"
    revision: "{{ .Release.Revision }}"
    time: "{{ now | unixEpoch }}"
data:
  spring_datasource_password: cGVyZmVjdHBhc3N3b3Jk
