{{- if .Values.backend.ingressAdmin.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name:  "{{ .Values.backend.name }}-admin"
  labels:
    app: "{{ .Values.backend.name }}"
    namespace: "{{ .Release.Namespace }}"
    revision: "{{ .Release.Revision }}"
    time: "{{ now | unixEpoch }}"
spec:
  rules:
  - host: "{{ .Values.backend.ingressAdmin.host }}"
    http:
      paths:
      - path: "{{ .Values.backend.ingressAdmin.path }}"
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.backend.name }}"
            port:
              number: {{ .Values.backend.servicePortAdmin }}
{{end}}