apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.frontend.name }}"
spec:
  ports:
  - port: {{ .Values.frontend.servicePort }}
    targetPort: {{ .Values.frontend.containerPort }}
    protocol: TCP
  selector:
    app:  "{{ .Values.frontend.name }}"
  type: ClusterIP
